[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared/" }
reqwest = { version = "0.12.24", features = ["json"] }
thiserror = "2.0.11"
serde = "1.0.217"
