[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
client = { path = "../client/" }
shared = { path = "../shared/" }
ratatui = "0.29.0"
anyhow = "1.0.100"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
better-panic = "0.3.0"
