[package]
name = "producer"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../../shared/" }
client = { path = "../../client/" }
clap = { version = "4.5.17", features = ["derive"] }
anyhow = "1.0.95"
tokio = { version = "1", features = ["full"] }
