[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bytes = "1"
serde = "1.0.217"
thiserror = "2.0.11"
chrono = "0.4.41"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
murmur2 = "0.1.0"
