name: Continuous Integration

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    ci:
        runs-on: ubuntu-latest
        name: Continuous Integration
        steps:
            - uses: actions/checkout@v4
            - uses: nixbuild/nix-quick-install-action@v30
            - name: Restore and save Nix store
              uses: nix-community/cache-nix-action@v6
              with:
                primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
                restore-prefixes-first-match: nix-${{ runner.os }}-
                gc-max-store-size-linux: 1G
                purge: true
                purge-prefixes: nix-${{ runner.os }}-
            - uses: nicknovitski/nix-develop@v1
            - name: cargo test
              run: cargo test
            - name: cargo test (ignored)
              run: cargo test -- --ignored
            - name: cargo clippy
              run: cargo clippy -- -D warnings
            - name: cargo fmt
              run: cargo fmt --check
